from peewee import *
from model.basemodel import BaseModel


class CambioMaterial(BaseModel):
    kWh = BooleanField(null=True)
    kvarh = BooleanField(null=True)
    kW = BooleanField(null=True)
    perfilCarga = BooleanField(null=True)
    compensacion = BooleanField(null=True)
    descripcionMedidor = CharField(100, null=True)
    aluminio = BooleanField(null=True)
    antihurto = BooleanField(null=True)
    subterranea = BooleanField(null=True)
    descripcionAcometida = CharField(100, null=True)
    tableroMetalico = BooleanField(null=True)
    descripcionTableroMetalico = CharField(100, null=True)
    tableroAntihurto = BooleanField(null=True)
    descripciontableroAntihurto = CharField(100, null=True)
    cableNumero6 = BooleanField(null=True)
    descripcionCableNumero6 = CharField(100, null=True)
    conductorNumero8 = BooleanField(null=True)
    descripcionConductorNumero8 = CharField(100, null=True)
    protectorTermico = BooleanField(null=True)
    descripcionProtectorTermico = CharField(100, null=True)
    candadoMaster = BooleanField(null=True)
    descripcionCandadoMaster = CharField(100, null=True)
    TPs = BooleanField(null=True)
    descripcionTPs = CharField(100, null=True)
    TCs = BooleanField(null=True)
    descripcionTCs = CharField(100, null=True)
    tarfia = BooleanField(null=True)
    descripcionTarifa = CharField(100, null=True)
    otros = CharField(100, null=True)